### ISSUE TITLE
请教 libffi 调用 C++ 虚函数报错问题

### ISSUE THREAD

**Issue by Hcount** [jilinxiaohuo/dump#1]
## 系统版本
MacBook Pro
Apple M1
MacOS 14.4.1 (23E224)
Xcode Version 15.3 (15E204a)

LLVM Version 16.0
libffi Version 3.4.6

## 问题描述
我在使用 LLVM 源码，构建解释器引擎，通过解释执行 IR 文件实现函数调用，对于非 IR 文件内的外部函数，借助了 libffi 工具。目前遇到的问题是，调用 C++ 虚函数报错，其他函数能够正常运行。不知道您是否遇到过相关的问题，过来请教下解决思路，非常感谢。

相关的源码如下：

### C++ 带有虚函数的类

```
class Animal {
public:
    virtual void speak(int arg) const {
      std::cout << "Animal makes a sound: " << arg << std::endl;
    }
    void info() const {
      std::cout << "This is an animal." << std::endl;
    }
};

class Dog : public Animal {
public:
    void speak(int arg) const override {
      std::cout << "Dog barks: " << arg << std::endl;
    }
    void fetch() const {
      std::cout << "Dog fetches the ball." << std::endl;
    }
};
```
speak 是一个虚函数，在通过 libffi 调用时程序会崩溃，前提是在 LLVM 解析 IR 的流程，正常使用 libffi 调用没问题。

### 调用此 C++ 类的函数

```
void IRTest01Func23_O(int arg1, double arg2)
{
  Dog anm = Dog();
  cppClassTest_paramObj(anm);
}
```

这个函数会转成 IR 中间表示，使用 LLVM 标准解释器解释执行，IR 代码如下：

```
; Function Attrs: mustprogress noinline optnone ssp uwtable(sync)
define void @_Z16IRTest01Func23_Oid(i32 noundef %0, double noundef %1) #0 {
  %3 = alloca i32, align 4
  %4 = alloca double, align 8
  %5 = alloca %class.Dog, align 8
  store i32 %0, ptr %3, align 4
  store double %1, ptr %4, align 8
  %6 = call i32 (ptr, ...) @printf(ptr noundef @.str.94)
  call void @llvm.memset.p0.i64(ptr align 8 %5, i8 0, i64 8, i1 false)
  %7 = call noundef ptr @_ZN3DogC1Ev(ptr noundef nonnull align 8 dereferenceable(8) %5) #6
  call void @_Z21cppClassTest_paramObjR6Animal(ptr noundef nonnull align 8 dereferenceable(8) %5)
  ret void
}
```

_Z21cppClassTest_paramObjR6Animal 就是要调用的外部函数，对应的源码函数名是 cppClassTest_paramObj

### cppClassTest_paramObj 函数的源码如下：

```
void cppClassTest_paramObj(Animal& animal)
{
  printf("~>> ✅✅ cppClassTest_paramObj\n");

  animal.speak(5); // 输出: Animal makes a sound.
  animal.info();  // 输出: This is an animal.
}
```

cppClassTest_paramObj 这个函数并不会转成 IR 中间表示，为了分析问题，我手动转换了，IR 代码如下：

```
; Function Attrs: mustprogress noinline optnone ssp uwtable(sync)
define void @_Z21cppClassTest_paramObjR6Animal(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = call i32 (ptr, ...) @printf(ptr noundef @.str.31)
  %4 = load ptr, ptr %2, align 8
  %5 = load ptr, ptr %4, align 8
  %6 = getelementptr inbounds ptr, ptr %5, i64 0
  %7 = load ptr, ptr %6, align 8
  call void %7(ptr noundef nonnull align 8 dereferenceable(8) %4, i32 noundef 5)
  %8 = load ptr, ptr %2, align 8
  call void @_ZNK6Animal4infoEv(ptr noundef nonnull align 8 dereferenceable(8) %8)
  ret void
}
```

在调用 animal.speak(5) 时程序崩溃，对应的 IR 代码是  call void %7(ptr noundef nonnull align 8 dereferenceable(8) %4, i32 noundef 5)。我的理解是，虚函数存储在虚函数表里，%7 这个函数指针，libffi 无法找到具体的函数实现，区分不出来是父类还是派生类。

![image](https://github.com/user-attachments/assets/ade9da77-4bd9-4488-941a-c2b35b26d920)
![image](https://github.com/user-attachments/assets/48de85ae-5a26-499b-9d82-25eb87046de0)
![image](https://github.com/user-attachments/assets/148a57e7-57ad-484a-83de-d79cecb28e30)

直接使用 libffi 调用是没问题的，比如下面的代码可以正常运行，结果符合预期：

```
void testFFIVirtual()
{
  // 准备libffi调用
  ffi_cif cif;
  ffi_type* argTypes[1] = { &ffi_type_pointer };
  if (ffi_prep_cif(&cif, FFI_DEFAULT_ABI, 1, &ffi_type_void, argTypes) == FFI_OK)
  {    
    Dog* myObject = new Dog();
    void* values[1] = { &myObject };
    void (*func)(Animal&) = cppClassTest_paramObj;

    ffi_call(&cif, FFI_FN(func), NULL, values);
  }
}
```

### 我在 LLVM 中调用 libffi 时，参数是通过 LLVM 解析 IR 后拿到的。相关的函数是 ffiTypeFor()、ffiValueFor()、ffiInvoke()。

目前看虚函数需要特殊处理，不过我没有好的思路，不知道应该从哪儿入手，感谢您抽出的宝贵时间。

**Comment by jilinxiaohuo** [comment]
你好，很抱歉才看见你的消息，不知道你的问题是否已经解决了。我自己写了一个脚本，通过ffi调用c++方法是可以调用虚函数的。方法是通过对象的地址，和成员函数指针拿到虚函数的地址，然后传递给libffi进行调用，这里需要注意的就是不同abi下，成员函数指针的实现方式不同。

ZackHan ***@***.***>于2024年12月3日 周二10:49写道：

**Comment by Hcount** [comment]
非常感谢您的解答。
问题应该如您所说，对象的虚表指针是错误的。libffi 需要一个正确的函数地址才能实现函数的调用。

### ExternalFunctions.cpp 类中，调用 ffiInvoke 时传递了以下参数：
```
static bool ffiInvoke(RawFunc Fn, Function *F, ArrayRef<GenericValue> ArgVals,
                      const DataLayout &TD, GenericValue &Result)
```
这些参数里我没有找到获取虚函数表相关的 API。

如果有任何可用的建议，非常感谢您能提出☕️☕️，目前不知道我的方案是否可行。
